export type Lang = 'en' | 'ru';
export type LightMode = 'sun' | 'spot' | 'top';
export type ShadowMethod = 'SM' | 'PCF' | 'PCSS' | 'VSM';

export type ShadowParams = {
  shadowMapSize: number;
  bias: number;
  method: ShadowMethod;
  pcfRadius?: number;
  pcfSamples?: number;
  pcssLightSize?: number;
  pcssBlockerSearchSamples?: number;
  vsmMinVariance?: number;
  vsmLightBleedReduction?: number;
  shadowStrength?: number;
};

export type MeshOption = { id: number; name: string };
export type ControlPanelStrings = typeof import('./constants').STRINGS[Lang];

export type ControlPanelProps = {
  onParamsChange: (params: ShadowParams) => void;
  onLoadModel: (file: File) => void;
  onResetScene?: () => void;
  onResetModel?: () => void;
  fps?: number;
  isPointerLocked?: boolean;
  lightMode: LightMode;
  onLightModeChange: (mode: LightMode) => void;
  onLoadObjectTexture?: (file: File) => void;
  onLoadFloorTexture?: (file: File) => void;
  lang: Lang;
  onLanguageChange: (lang: Lang) => void;
  autoRotate: boolean;
  onToggleAutoRotate: () => void;
  showFloor: boolean;
  showWalls: boolean;
  floorColor: string;
  wallColor: string;
  onShowFloorChange: (value: boolean) => void;
  onShowWallsChange: (value: boolean) => void;
  onFloorColorChange: (hex: string) => void;
  onWallColorChange: (hex: string) => void;
  objectMoveSpeed: number;
  onObjectMoveSpeedChange: (value: number) => void;
  lightIntensity: number;
  onLightIntensityChange: (value: number) => void;
  showLightBeam: boolean;
  onShowLightBeamChange: (value: boolean) => void;
  lightColor: string;
  onLightColorChange: (hex: string) => void;
  lightCount: number;
  activeLightIndex: number;
  onSelectLight: (index: number) => void;
  onAddLight: () => void;
  onRemoveLight: () => void;
  objectCount: number;
  activeObjectIndex: number;
  onSelectObject: (index: number) => void;
  onAddObject: () => void;
  onRemoveObject: () => void;
  onSaveScene?: () => void;
  onLoadSceneFile?: (file: File) => void;
  objectColor: string;
  onObjectColorChange: (hex: string) => void;
  objectCastShadows: boolean;
  onObjectCastShadowsChange: (value: boolean) => void;
  objectReceiveShadows: boolean;
  onObjectReceiveShadowsChange: (value: boolean) => void;
  lightCastShadows: boolean;
  onLightCastShadowsChange: (value: boolean) => void;
  meshOptions: MeshOption[];
  activeMeshId: number;
  onObjectMeshChange: (meshId: number) => void;
  objectSpecular: number;
  onObjectSpecularChange: (value: number) => void;
  objectShininess: number;
  onObjectShininessChange: (value: number) => void;
};
