import type { PerformanceMetrics } from '../../engine/types';
import type { ScenePresetId } from '../../engine/presets';

export type { PerformanceMetrics };

export type Lang = 'en' | 'ru';
export type LightMode = 'sun' | 'spot' | 'top';
export type ShadowMethod = 'SM' | 'PCF' | 'PCSS' | 'VSM';
export type ShadowDebugSlot = `slot${0 | 1 | 2 | 3 | 4 | 5 | 6 | 7}`;
export type ShadowDebugMode = 'off' | 'primary' | 'secondary' | ShadowDebugSlot;
export type LightDebugMode = 'final' | 'lighting' | 'diffuse' | 'specular' | 'shadow' | 'normals';
export type ScenePresetSelection = 'custom' | ScenePresetId;

export type ShadowParams = {
  shadowMapSize: number;
  bias: number;
  method: ShadowMethod;
  pcfRadius?: number;
  pcfSamples?: number;
  pcssLightSize?: number;
  pcssBlockerSearchSamples?: number;
  vsmMinVariance?: number;
  vsmLightBleedReduction?: number;
  shadowStrength?: number;
  ambientStrength?: number;
  exposure?: number;
  hemisphereSkyColor?: [number, number, number];
  hemisphereGroundColor?: [number, number, number];
  lightDebugMode?: LightDebugMode;
  debugShadowMap?: ShadowDebugMode;
};

export type MeshOption = { id: number; name: string };
export type ObjectScale = [number, number, number];
export type ControlPanelStrings = typeof import('./constants').STRINGS[Lang];

export type ControlPanelProps = {
  onParamsChange: (params: ShadowParams) => void;
  onLoadModel: (file: File) => void;
  onResetScene?: () => void;
  onResetModel?: () => void;
  onLightingPreset?: () => void;
  activeScenePreset: ScenePresetSelection;
  onScenePresetChange: (presetId: ScenePresetId) => void;
  isPointerLocked?: boolean;
  lightMode: LightMode;
  onLightModeChange: (mode: LightMode) => void;
  onLoadObjectTexture?: (file: File) => void;
  onLoadFloorTexture?: (file: File) => void;
  lang: Lang;
  onLanguageChange: (lang: Lang) => void;
  autoRotate: boolean;
  onToggleAutoRotate: () => void;
  showFloor: boolean;
  showWalls: boolean;
  floorSize: number;
  showGrid: boolean;
  floorColor: string;
  wallColor: string;
  onShowFloorChange: (value: boolean) => void;
  onShowWallsChange: (value: boolean) => void;
  onFloorSizeChange: (value: number) => void;
  onShowGridChange: (value: boolean) => void;
  onFloorColorChange: (hex: string) => void;
  onWallColorChange: (hex: string) => void;
  objectMoveSpeed: number;
  onObjectMoveSpeedChange: (value: number) => void;
  lightIntensity: number;
  onLightIntensityChange: (value: number) => void;
  showLightBeam: boolean;
  onShowLightBeamChange: (value: boolean) => void;
  lightColor: string;
  onLightColorChange: (hex: string) => void;
  lightCount: number;
  activeLightIndex: number;
  lightNames: string[];
  onSelectLight: (index: number) => void;
  onAddLight: () => void;
  onRemoveLight: () => void;
  onRenameLight: (index: number, name: string) => void;
  objectCount: number;
  activeObjectIndex: number;
  objectNames: string[];
  onSelectObject: (index: number) => void;
  onAddObject: () => void;
  onRemoveObject: () => void;
  onRenameObject: (index: number, name: string) => void;
  onSaveScene?: () => void;
  onLoadSceneFile?: (file: File) => void;
  onExportCsv?: () => void;
  onExportPdf?: () => void;
  onExportScreenshot?: () => void;
  objectColor: string;
  onObjectColorChange: (hex: string) => void;
  objectScale: ObjectScale;
  onObjectScaleChange: (scale: ObjectScale) => void;
  objectCastShadows: boolean;
  onObjectCastShadowsChange: (value: boolean) => void;
  objectReceiveShadows: boolean;
  onObjectReceiveShadowsChange: (value: boolean) => void;
  objectSelfShadows: boolean;
  onObjectSelfShadowsChange: (value: boolean) => void;
  spotInnerConeDeg: number;
  onSpotInnerConeDegChange: (value: number) => void;
  spotOuterConeDeg: number;
  onSpotOuterConeDegChange: (value: number) => void;
  spotRange: number;
  onSpotRangeChange: (value: number) => void;
  spotFalloff: number;
  onSpotFalloffChange: (value: number) => void;
  meshOptions: MeshOption[];
  activeMeshId: number;
  onObjectMeshChange: (meshId: number) => void;
  objectSpecular: number;
  onObjectSpecularChange: (value: number) => void;
  objectShininess: number;
  onObjectShininessChange: (value: number) => void;
  objectRoughness: number;
  onObjectRoughnessChange: (value: number) => void;
};
